### PR TITLE
Publish publicly

### PR DESCRIPTION
**Pull request by rvdh**

### CODE REVIEW

**Comment by rvdh** [comment]
> Is this explicitly needed like this?

Yeah. But probably only needed for the first publish.

**Comment by ChrisTerBeke** [comment]
ugh waiting for GitLab to sync

**Comment by rvdh** [comment]
> ugh waiting for GitLab to sync

Not gonna happen / the sync is probably fine but theres no build job to report a 'succesful' status.

**Comment by ChrisTerBeke** [comment]
Is the yaml config incorrect then?

**Comment by rvdh** [comment]
Thats a matter of perspective.. there simply is no build/test job. You might see that as an error :)

**Comment by ChrisTerBeke** [comment]
I guess we need some kind of linting on this at least?

**Comment by ianpaschal** [comment]
I guess we can have it lint itself?

**Comment by ianpaschal** [comment]
@ChrisTerBeke @rvdh I added the ability for it to lint itself (and fixed the 48 errors!). Should I add it to this PR?

**Comment by ChrisTerBeke** [comment]
yes please :) we can add it as 'test' stage in the CI

**Comment by matijs** [comment]
Before we publish… Yesterday I heard some doubts about the usage of yarn in [react-web-components](https://github.com/Ultimaker/react-web-components). If we want to switch from yarn (back) to npm, this might be a good repo to start with.

**Comment by ianpaschal** [comment]
That's a very good point @matijs

**Comment by ianpaschal** [comment]
🍏 💚 📗 🥗

**Pull request merged**
